/* webView: one forest-layers web drawn at runtime as SVG over forest-layers-bg.svg, from
   build/webs.json (generated by make_webs.py). Nodes are real buttons; arrows are drawn by kind:
   harms (solid pink), helps (dashed amber), partners (dotted green), named together (dashed grey). */
(function () {
  'use strict';
  var NYBG = window.NYBG, h = NYBG.h, s = NYBG.s, S = NYBG.store;

  var ICONS = {
    plant: 'M12 21V10M12 14c-3.5 0-6-2.2-6-6 3.5 0 6 2.2 6 6zM12 11c3 0 5-2 5-5-3 0-5 2-5 5z',
    tree: 'M12 22v-6M12 3 6 12h3l-3 4h12l-3-4h3z',
    fungus: 'M4 11a8 8 0 0 1 16 0zM10 11v8a2 2 0 0 0 4 0v-8',
    worm: 'M3 14c2-4 4-4 6 0s4 4 6 0 4-4 6 0',
    insect: 'M12 7v12M12 9c-2-4-7-5-8-2s3 6 8 5c-4 1-6 4-4 6s4-1 4-4M12 9c2-4 7-5 8-2s-3 6-8 5c4 1 6 4 4 6s-4-1-4-4',
    salamander: 'M4 15c3-1 4-5 8-5s6 3 8 2M8 13l-2 3M10 11l-1-3M15 11l1-3M17 12l2 3',
    deer: 'M9 21v-5l-2-5h10l-2 5v5M7 11 5 6M5 6 3 4M5 6l1-3M17 11l2-5M19 6l2-2M19 6l-1-3',
    invader: 'M12 21V9M12 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM12 13c-3 0-5-1.5-6-4M12 15c3 0 5-1.5 6-4',
    water: 'M3 9c2-2 4-2 6 0s4 2 6 0 4-2 6 0M3 15c2-2 4-2 6 0s4 2 6 0 4-2 6 0',
    people: 'M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM4 21a8 8 0 0 1 16 0',
    wind: 'M3 8h11a3 3 0 1 0-3-3M3 12h16a3 3 0 1 1-3 3M3 16h8',
    bird: 'M3 12c3-4 6-4 9 0 3-4 6-4 9 0M8 16c2-2 6-2 8 0',
    seed: 'M12 3c4 4 6 8 6 11a6 6 0 0 1-12 0c0-3 2-7 6-11zM12 9v8'
  };
  var KIND = { harm: 'Harms', help: 'Helps', mutual: 'Partners', link: 'Named together' };
  var COLOR = { harm: 'var(--edge-harm)', help: 'var(--edge-help)', mutual: 'var(--edge-mutual)', link: 'var(--edge-link)' };
  var uid = 0;

  function color(group) { return ICONS[group] ? 'var(--g-' + group + ')' : 'var(--ink-soft)'; }

  /* A gently curved path between two node centers, trimmed so arrowheads sit outside the rings. */
  function edgePath(a, b, trimA, trimB) {
    var dx = b.x - a.x, dy = b.y - a.y, len = Math.hypot(dx, dy) || 1;
    var ux = dx / len, uy = dy / len;
    var x1 = a.x + ux * trimA, y1 = a.y + uy * trimA, x2 = b.x - ux * trimB, y2 = b.y - uy * trimB;
    var bend = Math.min(28, len * 0.12);
    var cx = (x1 + x2) / 2 - uy * bend, cy = (y1 + y2) / 2 + ux * bend;
    return 'M' + x1.toFixed(1) + ' ' + y1.toFixed(1) + ' Q' + cx.toFixed(1) + ' ' + cy.toFixed(1) + ' ' + x2.toFixed(1) + ' ' + y2.toFixed(1);
  }

  function markers(prefix) {
    return s('defs', null, Object.keys(COLOR).map(function (k) {
      return s('marker', { id: prefix + k, viewBox: '0 0 10 10', refX: '7', refY: '5', markerWidth: '4.5', markerHeight: '4.5', orient: 'auto-start-reverse', markerUnits: 'strokeWidth' },
        s('path', { d: 'M0 0 L10 5 L0 10 Z', style: 'fill: ' + COLOR[k] }));
    }));
  }

  function edgesSvg(web, prefix, thin) {
    var pos = {};
    web.nodes.forEach(function (n) { pos[n.id] = n; });
    return s('svg', { viewBox: '0 0 390 560', 'aria-hidden': 'true', focusable: 'false', preserveAspectRatio: 'none' },
      thin ? null : markers(prefix),
      web.edges.map(function (e) {
        var a = pos[e.from], b = pos[e.to];
        if (!a || !b) return null;
        var attrs = { class: 'web-edge ' + (KIND[e.sign] ? e.sign : 'link'), d: edgePath(a, b, thin ? 0 : 36, thin ? 0 : 38) };
        if (thin) attrs.style = 'stroke-width: 8';
        else if (e.sign !== 'link') {
          attrs['marker-end'] = 'url(#' + prefix + e.sign + ')';
          if (e.sign === 'mutual') attrs['marker-start'] = 'url(#' + prefix + e.sign + ')';
        }
        return s('path', attrs);
      }));
  }

  /* Interactive web. opts: {onPick(i)} -> {el, select(i)} */
  function create(web, opts) {
    var links = S.webLinks(web.id);
    var prefix = 'w' + (++uid) + '-';
    var buttons = web.nodes.map(function (n, i) {
      var b = h('button', { type: 'button', class: 'node', style: { left: n.x + 'px', top: n.y + 'px', '--c': color(n.group) },
          'aria-label': n.name + ': ' + (n.step || '') + (links[n.id] && links[n.id].linksOut ? ' (links to other pages)' : '') },
        h('span', { class: 'ring' }, s('svg', { class: 'ic', width: 26, height: 26, viewBox: '0 0 24 24', 'aria-hidden': 'true' }, s('path', { d: ICONS[n.group] || ICONS.plant }))),
        links[n.id] && links[n.id].linksOut ? h('span', { class: 'link', 'aria-hidden': 'true' }, NYBG.icon('external', 11, { style: 'stroke-width: 3' })) : null,
        h('span', { class: 'lbl' }, n.short || n.name));
      b.addEventListener('click', function () { opts.onPick(i); });
      return b;
    });
    var el = h('div', { class: 'web' },
      h('img', { src: S.layersBg(), alt: '' }),
      edgesSvg(web, prefix, false),
      /* Layer names run up the left edge of each band (forest-layers-bg.svg: canopy 0-130,
         understory 130-262, floor 262-372, soil 372-560), clear of the generated node positions. */
      [['Canopy', 0, 130, '--layer-canopy'], ['Understory', 130, 262, '--layer-canopy'], ['Forest floor', 262, 372, '--layer-floor'], ['Soil', 372, 560, '--layer-soil']]
        .map(function (b) {
          return h('span', { class: 'web-layer', 'aria-hidden': 'true', style: { top: (b[1] + 6) + 'px', height: (b[2] - b[1] - 12) + 'px', color: 'var(' + b[3] + ')' } }, b[0]);
        }),
      buttons);
    return {
      el: el,
      select: function (i) { buttons.forEach(function (b, j) { b.classList.toggle('is-on', i === j); }); },
      button: function (i) { return buttons[i]; }
    };
  }

  /* Small picture of a web for the species-page card (decorative). */
  function thumb(web) {
    var svg = edgesSvg(web, '', true);
    svg.insertBefore(s('image', { href: S.layersBg(), x: 0, y: 0, width: 390, height: 560, preserveAspectRatio: 'none' }), svg.firstChild);
    web.nodes.forEach(function (n) {
      svg.appendChild(s('circle', { cx: n.x, cy: n.y, r: 30, style: 'fill: var(--paper); stroke: ' + color(n.group) + '; stroke-width: 12' }));
    });
    return h('span', { class: 'web-thumb', 'aria-hidden': 'true' }, svg);
  }

  /* Text list of a web's arrows (for screen readers and anyone who prefers text). */
  function arrowList(web) {
    var name = {};
    web.nodes.forEach(function (n) { name[n.id] = n.name; });
    return web.edges.map(function (e) {
      return { kind: KIND[e.sign] || 'Named together', text: (name[e.from] || e.from) + ' ' + e.label + ' → ' + (name[e.to] || e.to) };
    });
  }

  NYBG.components.webView = { create: create, thumb: thumb, arrowList: arrowList, color: color, KIND: KIND };
})();
